export const en = {
  "auth.login.productName": "Baby MiniMemo",
  "auth.login.tagline": "Tiny moments. Calm care.",
  "auth.login.hero": "Coordinating baby care, one memo at a time.",
  "auth.login.appleButton": "Continue with Apple",
  "auth.login.googleButton": "Continue with Google",
  "auth.login.emailLabel": "Household email",
  "auth.login.passwordLabel": "Secure password",
  "auth.login.emailPlaceholder": "your@family.com",
  "auth.login.passwordPlaceholder": "Enter your password",
  "auth.login.submit": "Sign in",
  "auth.login.signupPrompt": "New family?",
  "auth.login.signupLink": "Start your care circle",
  "auth.login.deferredProviders": "Apple and Google sign-in are deferred until native provider setup.",
  "auth.login.divider": "Or continue with",
  "auth.login.remember": "Remember me",
  "auth.login.forgotDeferred": "Reset deferred",
  "auth.login.errorMissing": "Please enter your email and password",
  "auth.login.errorFallback": "Login failed",
  "auth.login.securityText": "End-to-end encrypted family data",
  "onboarding.goalQuestion.title": "What do you need help with first?",
  "onboarding.goalQuestion.subtitle": "Pick the care rhythm that matters most right now.",
  "onboarding.goalQuestion.option.sync.label": "Stay in sync with my partner",
  "onboarding.goalQuestion.option.sync.detail": "Everyone knows what happened last.",
  "onboarding.goalQuestion.option.logging.label": "Track feeds, diapers, and sleep",
  "onboarding.goalQuestion.option.logging.detail": "Build one calm baby log.",
  "onboarding.goalQuestion.option.reminders.label": "Never miss a reminder",
  "onboarding.goalQuestion.option.reminders.detail": "Gentle nudges for due-soon care.",
  "onboarding.goalQuestion.option.moments.label": "Capture local photo moments",
  "onboarding.goalQuestion.option.moments.detail": "Keep tiny memories on this device.",
  "onboarding.goalQuestion.option.household.label": "Coordinate our household",
  "onboarding.goalQuestion.option.household.detail": "Parents and family share one view.",
  "onboarding.goalQuestion.option.overnight.label": "Make overnight handoffs easier",
  "onboarding.goalQuestion.option.overnight.detail": "Less waking, less guessing.",
  "onboarding.goalQuestion.reassurance.title": "Tiny moments. Calm care.",
  "onboarding.goalQuestion.reassurance.body": "We will use this to shape your preview and keep setup focused.",
  "onboarding.painPoints.title": "What feels hardest right now?",
  "onboarding.painPoints.subtitle": "Choose anything that sounds familiar. This helps us shape your first handoff preview.",
  "onboarding.painPoints.option.missedHandoffs.label": "Not sure what happened last",
  "onboarding.painPoints.option.missedHandoffs.detail": "Feeds, diapers, sleep, and notes get fuzzy fast.",
  "onboarding.painPoints.option.partnerUpdates.label": "Keeping my partner updated",
  "onboarding.painPoints.option.partnerUpdates.detail": "Texts and memory are easy to miss.",
  "onboarding.painPoints.option.overnightConfusion.label": "Overnight confusion",
  "onboarding.painPoints.option.overnightConfusion.detail": "Who fed the baby at 3 AM?",
  "onboarding.painPoints.option.forgotReminders.label": "Forgetting the next care time",
  "onboarding.painPoints.option.forgotReminders.detail": "Feeding, medication, or tummy time.",
  "onboarding.painPoints.option.scatteredNotes.label": "Notes are scattered everywhere",
  "onboarding.painPoints.option.scatteredNotes.detail": "Paper, texts, and tired memory do not sync.",
  "onboarding.painPoints.option.photoMomentsBuried.label": "Photo moments get buried",
  "onboarding.painPoints.option.photoMomentsBuried.detail": "Tiny memories should be easy to find, locally.",
  "common.continue": "Continue",
  "home.title": "Leo's Relay",
  "home.synced": "Synced just now",
  "timeline.title": "Timeline",
  "timeline.filter.all": "All Events",
  "timeline.filter.growth": "Growth",
  "handoff.title": "Handoff",
  "reminders.title": "Reminders",
  "family.title": "Family & Household",
  "settings.title": "Settings",
  "settings.section.plan": "Your plan",
  "settings.section.coordination": "Shared coordination",
  "settings.section.features": "Features",
  "settings.section.account": "Account",
  "settings.plans": "Plans",
  "settings.planName": "Premium Plan",
  "settings.planMeta": "Renews Oct 12, 2024",
  "settings.manage": "Manage",
  "settings.family.subtitle": "Household coordination",
  "settings.reminders.subtitle": "Feeding and meds",
  "settings.growthTimeline": "Growth Timeline",
  "settings.growthTimeline.subtitle": "Local photo moments on this device",
  "settings.widgets": "Widgets",
  "settings.widgets.subtitle": "Device snapshot visibility",
  "settings.language": "Language",
  "settings.language.subtitle": "English now; German draft QA toggle",
  "settings.language.switchToGerman": "Switch to German draft",
  "settings.language.switchToEnglish": "Switch to English",
  "settings.plans.subtitle": "Premium and Family",
  "settings.account": "Profile & Account",
  "settings.account.subtitle": "Name, email, sign out",
  "account.signOut": "Sign out",
  "paywall.title": "Unlock calm baby care",
  "paywall.subtitle": "Keep feeds, sleep, diapers, memories, and handoffs in one shared place.",
  "paywall.benefit.handoff": "Shared handoff history",
  "paywall.benefit.logs": "Unlimited care logs",
  "paywall.benefit.reminders": "Gentle reminders",
  "paywall.benefit.photos": "Local photo memories",
  "paywall.benefit.caregivers": "Care-circle coordination",
  "paywall.plan.annual.name": "Annual",
  "paywall.plan.monthly.name": "Monthly",
  "paywall.plan.weekly.name": "Weekly",
  "paywall.cta.trial": "Try 3 Days Free",
  "paywall.cta.continue": "Continue",
  "paywall.restore": "Restore",
  "notifications.reminder.title": "BabyMinimo reminder",
  "notifications.reminder.body": "{title} is due soon.",
  "widgets.currentState.ready": "Current baby status",
  "widgets.currentState.signedOut": "Sign in to BabyMinimo",
  "errors.generic.title": "Something went wrong",
  "errors.generic.retry": "Try again",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.today": "Today",
  "common.justNow": "Just now",
  "common.noData": "No data",
  "common.startLogging": "Start logging",
  "common.stable": "Stable",
  "common.daily": "daily",
  "home.header.title": "{babyName}'s Relay",
  "home.header.synced": "Synced just now",
  "home.header.syncedWith": "Synced just now • {caregiverName}",
  "home.snapshot.lastFed": "Last fed",
  "home.snapshot.sleepToday": "Sleep today",
  "home.snapshot.lastDiaper": "Last diaper",
  "home.snapshot.dueNext": "Due next",
  "home.snapshot.feedMeta": "4oz • Sarah",
  "home.snapshot.sleepGoal": "Goal: 14h",
  "home.snapshot.diaperMeta": "Wet • David",
  "home.snapshot.dueNextValue": "Feeding",
  "home.snapshot.dueNextMeta": "in 45 minutes",
  "home.summary.title": "This Week's Summary",
  "home.summary.feeds": "↗ Feeds",
  "home.summary.sleep": "↘ Sleep",
  "home.summary.diapers": "Diapers",
  "home.quickActions.title": "Quick actions",
  "home.quickActions.feed": "Feed",
  "home.quickActions.diaper": "Diaper",
  "home.quickActions.sleep": "Sleep",
  "home.quickActions.more": "More",
  "home.wins.title": "Recent Wins",
  "home.wins.viewAll": "View all ›",
  "home.wins.weekStrong": "Week Strong",
  "home.wins.familySync": "Family Sync",
  "home.wins.careChampion": "Care Champion",
  "home.activity.open": "Open Baby Activity and Habit Tracker",
  "home.activity.eyebrow": "Baby activity",
  "home.activity.title": "Care rhythm tracker",
  "home.activity.latest": "Last touchpoint: {label}, {time}.",
  "home.activity.empty": "Feeds, diapers, naps, reminders, and moments will build a gentle habit signal here.",
  "home.activity.today": "Today",
  "home.activity.care": "Care",
  "home.activity.nudges": "Nudges",
  "timeline.filter.care": "Feeding",
  "timeline.filter.notes": "Notes",
  "timeline.search": "Search timeline",
  "timeline.searchPlaceholder": "Search feeds, diapers, memories...",
  "timeline.searchInputLabel": "Search timeline events",
  "timeline.clearSearch": "Clear timeline search",
  "timeline.settings": "Timeline display settings",
  "timeline.settingsTitle": "Timeline display",
  "timeline.settingsMeta": "Choose how events are ordered.",
  "timeline.sortNewest": "Newest first",
  "timeline.sortOldest": "Oldest first",
  "timeline.addMoment": "Add photo moment",
  "timeline.addMomentSubtitle": "Save a local baby memory to Timeline",
  "timeline.empty.title": "Start your story together",
  "timeline.empty.copy": "Every feeding, diaper change, nap, and milestone will appear here, building your family's shared memory.",
  "timeline.empty.logEvents": "Log care events",
  "timeline.empty.logEventsMeta": "Feedings, diapers, sleep, and more",
  "timeline.empty.seeWho": "See who did what",
  "timeline.empty.seeWhoMeta": "Every caregiver's actions appear automatically",
  "timeline.empty.cta": "＋ Add First Moment",
  "timeline.type.today": "TODAY",
  "timeline.type.yesterday": "YESTERDAY, 4:20 PM",
  "timeline.type.feeding": "FEEDING",
  "timeline.type.health": "HEALTH",
  "timeline.type.care": "CARE",
  "timeline.care.breastfeed": "Breastfeed",
  "timeline.care.bottle": "Bottle",
  "timeline.care.diaper": "Diaper",
  "timeline.care.sleep": "Sleep",
  "timeline.care.medication": "Medication",
  "timeline.care.breastfeedTitle": "{caregiver} fed Leo breastmilk.",
  "timeline.care.loggedTitle": "{caregiver} logged {eventType}.",
  "timeline.care.side": "{side} side",
  "timeline.care.durationMinutes": "{duration} min",
  "timeline.care.nursingSession": "Nursing session",
  "timeline.growth.defaultTitle": "The first big smile!",
  "timeline.growth.milestoneCopy": "Leo is exactly 6 weeks old today. Captured this while he was playing with Dad.",
  "timeline.growth.photoCopy": "A local photo moment saved {time}.",
  "timeline.growth.memoryCopy": "A small memory saved locally for your household.",
  "timeline.mediaSafety.title": "Local media safety",
  "timeline.mediaSafety.meta": "Photos stay on this device. Back up before deleting the app, clearing data, or changing phones.",
  "timeline.mediaSafety.backupReady": "{count} ready for backup",
  "timeline.mediaSafety.allTracked": "{count} tracked locally",
  "timeline.mediaSafety.missing": "{count} missing media",
  "album.timelineEntry.title": "Create album",
  "album.timelineEntry.meta": "Choose Growth moments and BabyMinimo frames",
  "album.timelineEntry.action": "Export",
  "album.eyebrow": "Growth album",
  "album.title": "Create album",
  "album.householdAttribution": "The Miller Household",
  "album.preview.meta": "{slots} photo slots · {type}",
  "album.preview.photoCount": "{count} photos",
  "album.layout.single": "Single",
  "album.layout.collage": "Collage",
  "album.frame.classic-cream": "Classic Cream",
  "album.frame.sage-keepsake": "Sage Keepsake",
  "album.frame.storybook-single": "Storybook",
  "album.frame.minimal-white": "Minimal White",
  "album.frame.soft-floral": "Soft Floral",
  "album.frame.milestone-card": "Milestone Card",
  "album.frame.print-shop-border": "Print Shop Border",
  "album.frame.tiny-toes": "Tiny Toes",
  "album.frame.welcome-home": "Welcome Home",
  "album.frame.moonlight-nap": "Moonlight Nap",
  "album.frame.little-star": "Little Star",
  "album.frame.heirloom-portrait": "Heirloom Portrait",
  "album.frame.two-together": "Two Together",
  "album.frame.little-moments-strip": "Little Moments Strip",
  "album.frame.first-smiles-grid": "First Smiles Grid",
  "album.frame.family-circle": "Family Circle",
  "album.frame.scrapbook-keepsake": "Scrapbook Keepsake",
  "album.frame.milestone-collage": "Milestone Collage",
  "album.frame.first-year-grid": "First Year Grid",
  "album.frame.grandparent-keepsake": "Grandparent Keepsake",
  "album.moments.title": "Growth moments",
  "album.moments.count": "{count} selected",
  "album.frames.title": "Album frames",
  "album.frames.page": "Page {page} of {pageCount}",
  "album.frames.previous": "Previous",
  "album.frames.next": "Next",
  "album.storybook.title": "Storybook timeline",
  "album.storybook.meta": "Remove any timeline item you do not want printed on this page.",
  "album.firstYear.title": "First year slots",
  "album.firstYear.empty": "Empty",
  "album.firstYear.filled": "Photo",
  "album.output.title": "Export format",
  "album.mediaBackup.meta": "Export records a local media manifest so photos and captions can be backed up together.",
  "album.output.pdf": "PDF album",
  "album.output.images": "Image pages",
  "album.customText.title": "Album text",
  "album.customText.meta": "Type titles and notes in your own language. BabyMinimo will not bake English into frame art.",
  "album.customText.titleLabel": "Title",
  "album.customText.noteLabel": "Note",
  "album.customText.titlePlaceholder": "Our little story",
  "album.customText.notePlaceholder": "Add a caption, dedication, or memory",
  "album.customText.defaultTitle": "Our little story",
  "album.customText.defaultNote": "Tiny moments, beautifully remembered.",
  "album.ready.title": "Local export preview ready",
  "album.ready.meta": "{format} · {frameName}",
  "album.ready.mediaBackup": "{count} media items included in backup manifest",
  "album.export.button": "Build local export",
  "handoff.loading.title": "Preparing handoff...",
  "handoff.loading.copy": "BabyMinimo is pulling the latest feed, diaper, sleep, and note details.",
  "handoff.status.sleeping": "Currently Sleeping",
  "handoff.status.awake": "Awake",
  "handoff.metric.feeding": "Feeding",
  "handoff.metric.diaper": "Diaper",
  "handoff.metric.sleep": "Sleep",
  "handoff.metric.health": "Health",
  "handoff.metric.healthValue": "98.6°",
  "handoff.metric.stableBy": "Stable · {caregiver}",
  "handoff.reminders.open": "Open reminders",
  "handoff.reminders.unavailable": "Reminders unavailable",
  "handoff.dueSoon.title": "Due Soon",
  "handoff.dueSoon.overdue": "{count} Overdue",
  "handoff.dueSoon.empty": "Nothing due right now",
  "handoff.dueSoon.wasDue": "Was due at {time}",
  "handoff.dueSoon.dueAt": "Due at {time}",
  "handoff.latestNote.title": "Latest Note",
  "handoff.latestNote.empty": "No notes yet",
  "log.quick.title": "Quick log",
  "log.quick.subtitle": "What would you like to log?",
  "log.option.breastfeed": "Breastfeed",
  "log.option.bottle": "Bottle",
  "log.option.diaper": "Diaper",
  "log.option.sleep": "Sleep",
  "log.option.medication": "Medication",
  "log.form.title": "Log Event",
  "log.category.feeding": "Feeding",
  "log.category.diaper": "Diaper",
  "log.category.sleep": "Sleep",
  "log.category.health": "Health",
  "log.form.eventTime": "Event Time",
  "log.form.notesLabel": "Notes (optional)",
  "log.form.notesPlaceholder": "Add a note...",
  "growth.add.title": "Add a moment",
  "growth.add.date": "May 24, 2024",
  "growth.add.choosePhoto": "Choose photo",
  "growth.add.typeLabel": "Moment type",
  "growth.add.type.milestone": "Milestone",
  "growth.add.type.photo": "Photo",
  "growth.add.type.memory": "Memory",
  "growth.add.titleLabel": "Title",
  "growth.add.titlePlaceholder": "First smile!",
  "growth.add.notesLabel": "Notes (optional)",
  "growth.add.notesPlaceholder": "She smiled at Dad today.",
  "growth.add.localNote": "Growth Timeline photos are stored locally on this device in v1.",
  "reminders.add.title": "Add a nudge",
  "reminders.add.subtitle": "Schedule care for your household",
  "reminders.input.placeholder": "Reminder title",
  "reminders.create": "Create reminder",
  "reminders.notifications.title": "Notifications",
  "reminders.notifications.demo": "Notifications are local on this device for the demo build.",
  "reminders.notifications.enabledMessage": "Reminder notifications are enabled on this device.",
  "reminders.notifications.offMessage": "Notifications are off. Reminders still stay visible in BabyMinimo.",
  "reminders.notifications.enabled": "Enabled",
  "reminders.notifications.enable": "Enable",
  "reminders.notifications.afterQuietHours": "Reminder scheduled after quiet hours.",
  "reminders.notifications.scheduled": "Reminder notification scheduled.",
  "reminders.notifications.savedNoPermission": "Reminder saved. Notifications are not enabled on this device.",
  "reminders.notifications.canceled": "Reminder notification canceled.",
  "reminders.customDetail": "Custom household nudge",
  "reminders.customDue": "Tomorrow, 8:00 AM",
  "reminders.section.active": "Active nudges",
  "reminders.section.total": "{count} total",
  "reminders.empty.title": "No reminders yet",
  "reminders.empty.copy": "Add a nudge for feeds, medicine, tummy time, or anything your household needs to remember.",
  "reminders.empty.action": "Add reminder",
  "reminders.afterQuietHours": "after quiet hours",
  "household.relationship.selectorLabel": "Relationship",
  "household.relationship.parent": "Parent",
  "household.relationship.partner": "Partner",
  "household.relationship.husband": "Husband",
  "household.relationship.grandparent": "Grandparent",
  "household.relationship.family": "Family",
  "household.relationship.nanny": "Nanny",
  "household.relationship.nurse": "Nurse",
  "household.relationship.babysitter": "Babysitter",
  "household.relationship.friend": "Friend",
  "household.relationship.other": "Other",
  "household.relationship.customLabel": "Custom relationship label",
  "household.relationship.customPlaceholder": "Add a label",
  "household.access.admin": "Admin Access",
  "household.access.member": "Member Access",
  "household.access.lastSyncRecent": "Last sync 2m ago",
  "family.subtitle": "Coordinating care together",
  "family.plan.badge": "Active coordination plan",
  "family.plan.title": "The Miller Household",
  "family.plan.meta": "Standard Family Plan • Renewing Oct 12",
  "family.plan.manage": "Manage members",
  "family.plan.caregiverAccess": "Member access",
  "family.members.title": "Household Members",
  "family.invite.short": "Invite",
  "family.expand.title": "Expand the circle",
  "family.invite.placeholder": "partner@family.com",
  "family.invite.button": "Invite member",
  "family.invite.queued": "Demo invite queued locally for {relationshipLabel}. Real email delivery is intentionally not wired in v1 demo.",
  "family.invite.restrictedTitle": "Invites are owner-only",
  "family.invite.restrictedCopy": "Ask the household owner or an admin to invite another member.",
  "onboarding.invite.title": "Shared care is better care.",
  "onboarding.invite.subtitle": "Stay in sync with the people who help care for Leo, without extra mental load.",
  "onboarding.invite.step": "Step 9 of 9",
  "onboarding.invite.emailLabel": "Partner's email",
  "onboarding.invite.emailPlaceholder": "partner@example.com",
  "onboarding.invite.householdName": "The Miller Household",
  "onboarding.invite.noteBefore": "They will get an invite to join",
  "onboarding.invite.noteAfter": "and view Leo's live handoff status.",
  "onboarding.invite.sent": "Invite sent for {relationshipLabel}. They will receive an email to join your household.",
  "onboarding.invite.send": "Send invite",
  "onboarding.invite.later": "I'll do this later",
  "widgets.title": "Widgets",
  "widgets.section.visibility": "Widget visibility",
  "widgets.show.title": "Show baby status widgets",
  "widgets.show.subtitle": "Updates this device's Home Screen widget.",
  "widgets.status.default": "Widgets update from this device when BabyMinimo refreshes Home.",
  "widgets.status.cleared": "Widget snapshot cleared on this device.",
  "widgets.status.off": "Widgets are off. No baby care snapshot is shown.",
  "widgets.status.on": "Widgets will update again from Home after the next refresh.",
  "widgets.section.privacy": "Privacy",
  "widgets.visible.title": "Visible on this device",
  "widgets.visible.subtitle": "Anyone who can see the widget can see this glanceable care state.",
  "widgets.visible.status": "current baby status",
  "widgets.visible.reminder": "due soon reminder",
  "widgets.visible.lastCare": "last feed, diaper, and sleep",
  "widgets.visible.updated": "last updated time",
  "widgets.hidden.notes": "notes and free-text details",
  "widgets.hidden.photos": "Growth Timeline photos",
  "widgets.hidden.account": "account, billing, and invite data",
  "widgets.section.reset": "Reset",
  "widgets.clear.title": "Clear widget snapshot",
  "widgets.clear.subtitle": "Blanks the widget until BabyMinimo writes a fresh local snapshot.",
  "widgets.clear.lastCleared": "Last cleared {time}",
  "widgets.clear.recently": "recently",
  "account.title": "Profile & Account",
  "account.section.personal": "Personal details",
  "account.fullName": "Full name",
  "account.emailAddress": "Email address",
  "account.section.security": "Security",
  "account.password": "Password",
  "account.passwordDeferred": "Password changes are deferred to production account security.",
  "account.deferred": "Deferred",
  "lifecycle.cleanup.completed": "Local cleanup completed.",
  "lifecycle.cleanup.blocked": "Local account cleanup could not finish. Please try again.",
  "lifecycle.cleanup.retry": "Some local cleanup will be retried the next time BabyMinimo opens.",
  "widgets.currentState.chooseBaby": "Choose a baby",
  "widgets.currentState.openApp": "Open the app",
  "widgets.currentState.noFeed": "No feed yet",
  "widgets.currentState.noDiaper": "No diaper yet",
  "widgets.currentState.noSleep": "No sleep yet",
  "widgets.currentState.nothingDue": "Nothing due",
  "widgets.currentState.caughtUp": "You are caught up.",
  "widgets.currentState.notSynced": "Not synced",
  "widgets.currentState.openBabyMinimo": "Open BabyMinimo",
  "widgets.currentState.stale": "May be out of date",
  "widgets.currentState.empty": "No care events yet",
  "widgets.currentState.sleeping": "Currently sleeping",
  "widgets.currentState.awake": "Currently awake",
  "widgets.currentState.dueSoon": "Due soon",
  "widgets.currentState.latestSnapshot": "Latest snapshot",
  "widgets.currentState.updated": "Updated {time}",
  "widgets.badge.live": "LIVE",
  "widgets.badge.stale": "STALE",
  "widgets.badge.refresh": "REFRESH",
  "widgets.badge.empty": "EMPTY",
  "widgets.badge.signIn": "SIGN IN",
  "widgets.badge.setup": "SETUP",
  "widgets.badge.off": "OFF",
  "log.feedingType": "Feeding type",
  "log.option.nursing": "Nursing",
  "log.sideDuration": "Side & duration",
  "log.side.left": "Left",
  "log.side.right": "Right",
  "log.side.both": "Both",
  "log.amount": "Amount",
  "log.milkType": "Milk type",
  "log.milk.breastmilk": "Breastmilk",
  "log.milk.formula": "Formula",
  "log.type": "Type",
  "log.diaper.wet": "Wet",
  "log.diaper.dirty": "Dirty",
  "log.diaper.both": "Both",
  "log.sleepState": "Sleep state",
  "log.sleep.crib": "Crib",
  "log.sleep.arms": "Arms",
  "log.sleep.other": "Other",
  "log.duration": "Duration",
  "log.medication": "Medication",
  "log.medication.placeholder": "Medication name",
  "log.medication.fallback": "Medication",
  "log.dose.placeholder": "Dose",
  "log.createdBy.fallback": "Caregiver",
  "widgets.currentState.signInNeeded": "Sign in needed",
  "widgets.currentState.widgetsOff": "Widgets are off",
  "account.delete.section": "Account deletion",
  "account.delete.title": "Delete account",
  "account.delete.subtitle": "Local demo cleanup and production deletion policy",
  "account.delete.warning": "This clears local BabyMinimo data on this device and signs you out. Production cloud deletion remains gated until backend purge is ready.",
  "account.delete.confirmTitle": "Delete account?",
  "account.delete.confirmCopy": "Type DELETE and enter your password to confirm local account cleanup for this device.",
  "account.delete.passwordLabel": "Current password",
  "account.delete.passwordPlaceholder": "Enter your password",
  "account.delete.confirmLabel": "Type DELETE",
  "account.delete.confirmPlaceholder": "DELETE",
  "account.delete.submit": "Delete local account data",
  "account.delete.submitting": "Deleting...",
  "account.delete.cancel": "Keep my account",
  "account.delete.error": "Enter your password and type DELETE to continue.",
  "account.delete.productionNote": "Production Firebase Auth deletion and shared household purge are handled by the later backend task.",
  "babySwitcher.open": "Choose baby",
  "babySwitcher.eyebrow": "Household babies",
  "babySwitcher.title": "Choose who you are tracking",
  "babySwitcher.copy": "Twins, triplets, and siblings stay in one household. BabyMinimo scopes logs, reminders, handoff, widgets, and memories to the selected baby.",
  "babySwitcher.count": "{count} babies",
  "babySwitcher.select": "Select {babyName}",
  "babySwitcher.birthDateMissing": "Birth date not set",
  "babySwitcher.empty": "Add your first baby to begin.",
  "babySwitcher.addTitle": "Add another baby",
  "babySwitcher.addSubtitle": "Use this for twins, triplets, or a new sibling.",
  "babySwitcher.namePlaceholder": "Baby's name",
  "babySwitcher.birthDatePlaceholder": "Birth date (optional)",
  "babySwitcher.addButton": "Add and switch",
  "babySwitcher.adding": "Adding...",
  "babySwitcher.error": "Enter a baby name before adding.",
  "settings.activity": "Baby Activity",
  "settings.activity.subtitle": "Habit tracker and care rhythm",
  "activity.title": "Baby Activity",
  "activity.defaultBaby": "Your baby",
  "activity.eyebrow": "{babyName}’s care rhythm",
  "activity.heroTitle": "See the rhythm of care",
  "activity.heroCopy": "BabyMinimo keeps recent logs, reminders, handoffs, baby switches, and local photo moments scoped to the selected baby.",
  "activity.stats.today": "Today",
  "activity.stats.care": "Care",
  "activity.stats.reminders": "Nudges",
  "activity.rhythmTitle": "Gentle habit signal",
  "activity.rhythmBodyWithActivity": "Last touchpoint: {label}, {time}.",
  "activity.rhythmBodyEmpty": "Start with one feed, diaper, nap, reminder, or moment. No streak pressure.",
  "activity.recentTitle": "Recent activity",
  "activity.empty.title": "No activity yet",
  "activity.empty.copy": "Care logs, reminders, handoffs, baby switches, and local photo moments will appear here for the selected baby.",
  "activity.detailFallback": "Saved locally for your household rhythm."
}

export type BabyMinimoTranslationKey = keyof typeof en
